//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  posts: Posts;
  postsConnection: PostsConnection;
  roles: Roles;
  rolesConnection: RolesConnection;
  whitepaper: Whitepaper;
  whitepaperConnection: WhitepaperConnection;
  glossary: Glossary;
  glossaryConnection: GlossaryConnection;
  ideology: Ideology;
  ideologyConnection: IdeologyConnection;
  team: Team;
  teamConnection: TeamConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
};


export type QueryRolesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRolesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RolesFilter>;
};


export type QueryWhitepaperArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWhitepaperConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WhitepaperFilter>;
};


export type QueryGlossaryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlossaryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossaryFilter>;
};


export type QueryIdeologyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIdeologyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IdeologyFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};

export type DocumentFilter = {
  posts?: InputMaybe<PostsFilter>;
  roles?: InputMaybe<RolesFilter>;
  whitepaper?: InputMaybe<WhitepaperFilter>;
  glossary?: InputMaybe<GlossaryFilter>;
  ideology?: InputMaybe<IdeologyFilter>;
  team?: InputMaybe<TeamFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Posts | Roles | Whitepaper | Glossary | Ideology | Team | Folder;

export type Posts = Node & Document & {
  __typename?: 'Posts';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  cardImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PostsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  cardImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type Roles = Node & Document & {
  __typename?: 'Roles';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  emoji?: Maybe<Scalars['String']['output']>;
  commitment: Scalars['String']['output'];
  responsibilities: Scalars['String']['output'];
  requirements: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RolesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  emoji?: InputMaybe<StringFilter>;
  commitment?: InputMaybe<StringFilter>;
  responsibilities?: InputMaybe<StringFilter>;
  requirements?: InputMaybe<StringFilter>;
};

export type RolesConnectionEdges = {
  __typename?: 'RolesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Roles>;
};

export type RolesConnection = Connection & {
  __typename?: 'RolesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RolesConnectionEdges>>>;
};

export type Whitepaper = Node & Document & {
  __typename?: 'Whitepaper';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WhitepaperFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type WhitepaperConnectionEdges = {
  __typename?: 'WhitepaperConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Whitepaper>;
};

export type WhitepaperConnection = Connection & {
  __typename?: 'WhitepaperConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WhitepaperConnectionEdges>>>;
};

export type Glossary = Node & Document & {
  __typename?: 'Glossary';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlossaryFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type GlossaryConnectionEdges = {
  __typename?: 'GlossaryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Glossary>;
};

export type GlossaryConnection = Connection & {
  __typename?: 'GlossaryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlossaryConnectionEdges>>>;
};

export type Ideology = Node & Document & {
  __typename?: 'Ideology';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IdeologyFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type IdeologyConnectionEdges = {
  __typename?: 'IdeologyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Ideology>;
};

export type IdeologyConnection = Connection & {
  __typename?: 'IdeologyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IdeologyConnectionEdges>>>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  role: Scalars['String']['output'];
  jobTitle: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  order: Scalars['Float']['output'];
  xUrl?: Maybe<Scalars['String']['output']>;
  farcasterUrl?: Maybe<Scalars['String']['output']>;
  lensUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TeamFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  jobTitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  order?: InputMaybe<NumberFilter>;
  xUrl?: InputMaybe<StringFilter>;
  farcasterUrl?: InputMaybe<StringFilter>;
  lensUrl?: InputMaybe<StringFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePosts: Posts;
  createPosts: Posts;
  updateRoles: Roles;
  createRoles: Roles;
  updateWhitepaper: Whitepaper;
  createWhitepaper: Whitepaper;
  updateGlossary: Glossary;
  createGlossary: Glossary;
  updateIdeology: Ideology;
  createIdeology: Ideology;
  updateTeam: Team;
  createTeam: Team;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationUpdateRolesArgs = {
  relativePath: Scalars['String']['input'];
  params: RolesMutation;
};


export type MutationCreateRolesArgs = {
  relativePath: Scalars['String']['input'];
  params: RolesMutation;
};


export type MutationUpdateWhitepaperArgs = {
  relativePath: Scalars['String']['input'];
  params: WhitepaperMutation;
};


export type MutationCreateWhitepaperArgs = {
  relativePath: Scalars['String']['input'];
  params: WhitepaperMutation;
};


export type MutationUpdateGlossaryArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossaryMutation;
};


export type MutationCreateGlossaryArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossaryMutation;
};


export type MutationUpdateIdeologyArgs = {
  relativePath: Scalars['String']['input'];
  params: IdeologyMutation;
};


export type MutationCreateIdeologyArgs = {
  relativePath: Scalars['String']['input'];
  params: IdeologyMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};

export type DocumentUpdateMutation = {
  posts?: InputMaybe<PostsMutation>;
  roles?: InputMaybe<RolesMutation>;
  whitepaper?: InputMaybe<WhitepaperMutation>;
  glossary?: InputMaybe<GlossaryMutation>;
  ideology?: InputMaybe<IdeologyMutation>;
  team?: InputMaybe<TeamMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  posts?: InputMaybe<PostsMutation>;
  roles?: InputMaybe<RolesMutation>;
  whitepaper?: InputMaybe<WhitepaperMutation>;
  glossary?: InputMaybe<GlossaryMutation>;
  ideology?: InputMaybe<IdeologyMutation>;
  team?: InputMaybe<TeamMutation>;
};

export type PostsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  cardImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type RolesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  emoji?: InputMaybe<Scalars['String']['input']>;
  commitment?: InputMaybe<Scalars['String']['input']>;
  responsibilities?: InputMaybe<Scalars['String']['input']>;
  requirements?: InputMaybe<Scalars['String']['input']>;
};

export type WhitepaperMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type GlossaryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type IdeologyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  jobTitle?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  xUrl?: InputMaybe<Scalars['String']['input']>;
  farcasterUrl?: InputMaybe<Scalars['String']['input']>;
  lensUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PostsPartsFragment = { __typename: 'Posts', title: string, slug: string, description: string, date?: string | null, author?: string | null, image?: string | null, cardImage?: string | null, body?: string | null };

export type RolesPartsFragment = { __typename: 'Roles', title: string, slug: string, emoji?: string | null, commitment: string, responsibilities: string, requirements: string };

export type WhitepaperPartsFragment = { __typename: 'Whitepaper', title: string, slug: string, description?: string | null, body?: string | null };

export type GlossaryPartsFragment = { __typename: 'Glossary', title: string, slug: string, description?: string | null, body?: string | null };

export type IdeologyPartsFragment = { __typename: 'Ideology', title: string, slug: string, description?: string | null, body?: string | null };

export type TeamPartsFragment = { __typename: 'Team', title: string, slug: string, role: string, jobTitle: string, image?: string | null, order: number, xUrl?: string | null, farcasterUrl?: string | null, lensUrl?: string | null };

export type PostsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostsQuery = { __typename?: 'Query', posts: { __typename: 'Posts', id: string, title: string, slug: string, description: string, date?: string | null, author?: string | null, image?: string | null, cardImage?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
}>;


export type PostsConnectionQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostsConnectionEdges', cursor: string, node?: { __typename: 'Posts', id: string, title: string, slug: string, description: string, date?: string | null, author?: string | null, image?: string | null, cardImage?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type RolesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RolesQuery = { __typename?: 'Query', roles: { __typename: 'Roles', id: string, title: string, slug: string, emoji?: string | null, commitment: string, responsibilities: string, requirements: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type RolesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RolesFilter>;
}>;


export type RolesConnectionQuery = { __typename?: 'Query', rolesConnection: { __typename?: 'RolesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RolesConnectionEdges', cursor: string, node?: { __typename: 'Roles', id: string, title: string, slug: string, emoji?: string | null, commitment: string, responsibilities: string, requirements: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WhitepaperQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WhitepaperQuery = { __typename?: 'Query', whitepaper: { __typename: 'Whitepaper', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WhitepaperConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WhitepaperFilter>;
}>;


export type WhitepaperConnectionQuery = { __typename?: 'Query', whitepaperConnection: { __typename?: 'WhitepaperConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WhitepaperConnectionEdges', cursor: string, node?: { __typename: 'Whitepaper', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlossaryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlossaryQuery = { __typename?: 'Query', glossary: { __typename: 'Glossary', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GlossaryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossaryFilter>;
}>;


export type GlossaryConnectionQuery = { __typename?: 'Query', glossaryConnection: { __typename?: 'GlossaryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlossaryConnectionEdges', cursor: string, node?: { __typename: 'Glossary', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type IdeologyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IdeologyQuery = { __typename?: 'Query', ideology: { __typename: 'Ideology', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type IdeologyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IdeologyFilter>;
}>;


export type IdeologyConnectionQuery = { __typename?: 'Query', ideologyConnection: { __typename?: 'IdeologyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IdeologyConnectionEdges', cursor: string, node?: { __typename: 'Ideology', id: string, title: string, slug: string, description?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, title: string, slug: string, role: string, jobTitle: string, image?: string | null, order: number, xUrl?: string | null, farcasterUrl?: string | null, lensUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, title: string, slug: string, role: string, jobTitle: string, image?: string | null, order: number, xUrl?: string | null, farcasterUrl?: string | null, lensUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  __typename
  title
  slug
  description
  date
  author
  image
  cardImage
  body
}
    `;
export const RolesPartsFragmentDoc = gql`
    fragment RolesParts on Roles {
  __typename
  title
  slug
  emoji
  commitment
  responsibilities
  requirements
}
    `;
export const WhitepaperPartsFragmentDoc = gql`
    fragment WhitepaperParts on Whitepaper {
  __typename
  title
  slug
  description
  body
}
    `;
export const GlossaryPartsFragmentDoc = gql`
    fragment GlossaryParts on Glossary {
  __typename
  title
  slug
  description
  body
}
    `;
export const IdeologyPartsFragmentDoc = gql`
    fragment IdeologyParts on Ideology {
  __typename
  title
  slug
  description
  body
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  title
  slug
  role
  jobTitle
  image
  order
  xUrl
  farcasterUrl
  lensUrl
}
    `;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export const RolesDocument = gql`
    query roles($relativePath: String!) {
  roles(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RolesParts
  }
}
    ${RolesPartsFragmentDoc}`;
export const RolesConnectionDocument = gql`
    query rolesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RolesFilter) {
  rolesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RolesParts
      }
    }
  }
}
    ${RolesPartsFragmentDoc}`;
export const WhitepaperDocument = gql`
    query whitepaper($relativePath: String!) {
  whitepaper(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WhitepaperParts
  }
}
    ${WhitepaperPartsFragmentDoc}`;
export const WhitepaperConnectionDocument = gql`
    query whitepaperConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WhitepaperFilter) {
  whitepaperConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WhitepaperParts
      }
    }
  }
}
    ${WhitepaperPartsFragmentDoc}`;
export const GlossaryDocument = gql`
    query glossary($relativePath: String!) {
  glossary(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlossaryParts
  }
}
    ${GlossaryPartsFragmentDoc}`;
export const GlossaryConnectionDocument = gql`
    query glossaryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlossaryFilter) {
  glossaryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlossaryParts
      }
    }
  }
}
    ${GlossaryPartsFragmentDoc}`;
export const IdeologyDocument = gql`
    query ideology($relativePath: String!) {
  ideology(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IdeologyParts
  }
}
    ${IdeologyPartsFragmentDoc}`;
export const IdeologyConnectionDocument = gql`
    query ideologyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IdeologyFilter) {
  ideologyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IdeologyParts
      }
    }
  }
}
    ${IdeologyPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      },
    roles(variables: RolesQueryVariables, options?: C): Promise<{data: RolesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RolesQueryVariables, query: string}> {
        return requester<{data: RolesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RolesQueryVariables, query: string}, RolesQueryVariables>(RolesDocument, variables, options);
      },
    rolesConnection(variables?: RolesConnectionQueryVariables, options?: C): Promise<{data: RolesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RolesConnectionQueryVariables, query: string}> {
        return requester<{data: RolesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RolesConnectionQueryVariables, query: string}, RolesConnectionQueryVariables>(RolesConnectionDocument, variables, options);
      },
    whitepaper(variables: WhitepaperQueryVariables, options?: C): Promise<{data: WhitepaperQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhitepaperQueryVariables, query: string}> {
        return requester<{data: WhitepaperQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhitepaperQueryVariables, query: string}, WhitepaperQueryVariables>(WhitepaperDocument, variables, options);
      },
    whitepaperConnection(variables?: WhitepaperConnectionQueryVariables, options?: C): Promise<{data: WhitepaperConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhitepaperConnectionQueryVariables, query: string}> {
        return requester<{data: WhitepaperConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhitepaperConnectionQueryVariables, query: string}, WhitepaperConnectionQueryVariables>(WhitepaperConnectionDocument, variables, options);
      },
    glossary(variables: GlossaryQueryVariables, options?: C): Promise<{data: GlossaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaryQueryVariables, query: string}> {
        return requester<{data: GlossaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaryQueryVariables, query: string}, GlossaryQueryVariables>(GlossaryDocument, variables, options);
      },
    glossaryConnection(variables?: GlossaryConnectionQueryVariables, options?: C): Promise<{data: GlossaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaryConnectionQueryVariables, query: string}> {
        return requester<{data: GlossaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaryConnectionQueryVariables, query: string}, GlossaryConnectionQueryVariables>(GlossaryConnectionDocument, variables, options);
      },
    ideology(variables: IdeologyQueryVariables, options?: C): Promise<{data: IdeologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IdeologyQueryVariables, query: string}> {
        return requester<{data: IdeologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IdeologyQueryVariables, query: string}, IdeologyQueryVariables>(IdeologyDocument, variables, options);
      },
    ideologyConnection(variables?: IdeologyConnectionQueryVariables, options?: C): Promise<{data: IdeologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IdeologyConnectionQueryVariables, query: string}> {
        return requester<{data: IdeologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IdeologyConnectionQueryVariables, query: string}, IdeologyConnectionQueryVariables>(IdeologyConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  